import { Product, BottomNavItem } from './types';

export const mockProducts: Product[] = [
  {
    id: 'r2-absolute-bold',
    title: 'Absolute Bold',
    image: '/assets/products/r2-thumb-01.svg',
    badge: 'VIP',
    badgeType: 'vip',
    rating: 4.7,
    reviews: 246,
    originalPrice: 136000,
    price: 118000,
    discount: 13,
    stockStatus: 'ready',
  },
  {
    id: 'r2-age-pro',
    title: 'Age Pro',
    image: '/assets/products/r2-thumb-02.svg',
    badge: 'BARU',
    badgeType: 'new',
    rating: 4.8,
    reviews: 189,
    originalPrice: 75000,
    price: 65000,
    discount: 13,
    stockStatus: 'ready',
  },
  {
    id: 'r2-classic-filter',
    title: 'Classic Filter',
    image: '/assets/products/r2-thumb-03.svg',
    rating: 4.5,
    reviews: 312,
    price: 45000,
    stockStatus: 'ready',
  },
  {
    id: 'r2-premium-blend',
    title: 'Premium Blend',
    image: '/assets/products/r2-thumb-04.svg',
    badge: 'SALE',
    badgeType: 'sale',
    rating: 4.9,
    reviews: 428,
    originalPrice: 95000,
    price: 76000,
    discount: 20,
    stockStatus: 'limited',
  },
  {
    id: 'r2-elite-select',
    title: 'Elite Select',
    image: '/assets/products/r2-thumb-01.svg',
    rating: 4.6,
    reviews: 157,
    price: 89000,
    stockStatus: 'ready',
  },
  {
    id: 'r2-smooth-taste',
    title: 'Smooth Taste',
    image: '/assets/products/r2-thumb-02.svg',
    rating: 4.4,
    reviews: 203,
    price: 52000,
    stockStatus: 'ready',
  },
  {
    id: 'r2-signature-line',
    title: 'Signature Line',
    image: '/assets/products/r2-thumb-03.svg',
    badge: 'VIP',
    badgeType: 'vip',
    rating: 4.8,
    reviews: 334,
    originalPrice: 120000,
    price: 102000,
    discount: 15,
    stockStatus: 'ready',
  },
  {
    id: 'r2-ultra-premium',
    title: 'Ultra Premium',
    image: '/assets/products/r2-thumb-04.svg',
    rating: 5,
    reviews: 511,
    originalPrice: 150000,
    price: 127500,
    discount: 15,
    stockStatus: 'ready',
  },
];

export const bottomNavItems: BottomNavItem[] = [
  { id: 'home', label: 'Beranda', icon: 'home', route: '/' },
  { id: 'catalog', label: 'Katalog', icon: 'grid', route: '/products' },
  { id: 'cart', label: 'Keranjang', icon: 'cart', route: '/checkout', badge: 0 },
  { id: 'wishlist', label: 'Wishlist', icon: 'heart', route: '/products' },
  { id: 'whatsapp', label: 'WhatsApp', icon: 'whatsapp', route: '#' },
];
