import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/router'
import { supabase } from '../lib/supabaseClient'

const COLUMNS='Handle,Title,Vendor,Type,Tags,Published,Option1 Name,Option1 Value,Variant SKU,Variant Price,"Variant Inventory Qty",Status'
const money=v=>Number.isFinite(Number(v))?new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v)):'Harga belum tersedia'
const iconPaths={search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,shield:<><path d="M12 3 20 6v5c0 5-3.3 8.6-8 10-4.7-1.4-8-5-8-10V6l8-3Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/></>,truck:<><path d="M3 6h11v10H3zM14 9h4l3 3v4h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></>,box:<><path d="m4 7 8-4 8 4-8 4-8-4Z"/><path d="M4 7v10l8 4 8-4V7M12 11v10"/></>,check:<path d="m5 12 4 4L19 6"/>,map:<><path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Z"/><path d="M9 3v15M15 6v15"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,star:<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9L12 3Z"/>}
function Icon({name,size=20}){return <svg className="hx-icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{iconPaths[name]}</svg>}

const benefits=[['shield','Bayar Setelah Resi Keluar','100% Anti Penipuan','Pembayaran dilakukan setelah barang masuk ekspedisi dan resi terbit, sesuai konfirmasi transaksi.'],['truck','Gratis Ongkir','1 Bal (20 Slop)','Program subsidi ongkos kirim untuk minimal 1 bal (20 slop), sesuai ketentuan operasional.'],['box','233 Merek Ready Stock','R2 + Resmi','Katalog produksi aktif menampilkan produk yang tersedia dari database live.'],['check','100% Original','& Discreet Packing','Informasi produk dan stok berasal dari katalog distributor; detail packing mengikuti prosedur operasional.']]
const tabs=[['Subsidi Ongkir','Gratis ongkir langsung dari gudang tanpa syarat tersembunyi. Minimal 1 Bal (20 Slop).'],['Real-time Packing','Dokumentasi foto & video langsung dari gudang hingga packing. Mitra melihat pesanan disiapkan secara transparan.'],['Bayar Setelah Resi','Tidak ada transfer di awal. Tagihan dibayar setelah barang masuk ekspedisi dan resi terbit, sesuai kesepakatan transaksi.']]
const testimonials=[['H. Slamet Widodo','Toko Berkah Jaya, Surabaya','Sistem bayar setelah resi benar-benar menghilangkan rasa was-was. Resi keluar, baru saya transfer. Barang selalu sesuai video packing.'],['Siti Rahmawati','Warung Bu Siti, Makassar','Gratis ongkir 1 bal sangat membantu margin toko saya. Pengiriman ke Sulawesi tetap cepat.'],['Budi Santoso','Toko Sumber Rezeki, Jakarta','Katalog R2-nya lengkap, margin Smith Mild paling enak. Admin responsif.'],['Agus Priyanto','Grosir AP, Medan','Sudah 8x order, tidak pernah mengecewakan. Harga grosirnya jujur, stok selalu ready.'],['Dewi Lestari','Toko Dewi, Denpasar','Awalnya ragu karena jarak, tapi setelah lihat lokasi gudang di Maps dan video packing, langsung yakin.']]
const faqs=[['Apa itu sistem “Bayar Setelah Resi Keluar”?','Pembayaran baru dilakukan setelah barang masuk ekspedisi dan resi terbit. 100% anti penipuan.'],['Berapa minimal order untuk gratis ongkir?','Minimal 1 bal (20 slop), bisa campur merek.'],['Bagaimana alur pemesanannya?','Pilih merek → keranjang → checkout → admin konfirmasi via WhatsApp.'],['Ekspedisi apa saja yang tersedia?','JNE, J&T, SiCepat Express, Indah Cargo.'],['Berapa total pilihan merek?','Total 233 merek — 167 R2, 66 Resmi. Angka ini ditampilkan sebagai informasi katalog yang diberikan pemilik situs.'],['Di mana lokasi gudang fisik R2 Nusantara?','Gudang pusat kami berada di Kota Malang, Jawa Timur. Detail titik kunjungan dikonfirmasi melalui admin.']]
const picks=['Marlboro Gold Series','Dji Sam Soe Filter','Smith Mild']

function SearchBar({value,onChange,onSubmit,className=''}){return <form className={`hx-search ${className}`} role="search" onSubmit={onSubmit}><Icon name="search" size={21}/><input type="search" value={value} onChange={onChange} placeholder="Cari produk, kategori, merk, atau SKU..." aria-label="Cari produk, kategori, merk, atau SKU"/><button type="submit" aria-label="Cari">→</button></form>}

export default function HomepageExperience(){
 const router=useRouter()
 const [products,setProducts]=useState([]),[tab,setTab]=useState(0),[slide,setSlide]=useState(0),[open,setOpen]=useState(null),[cart,setCart]=useState(0),[search,setSearch]=useState('')
 useEffect(()=>{let mounted=true;supabase.from('R2 NUSANTARA').select(COLUMNS).eq('Published',true).eq('Status','active').limit(100).then(({data})=>{if(mounted)setProducts(data||[])});return()=>{mounted=false}},[])
 useEffect(()=>{const sync=()=>{try{setCart(JSON.parse(localStorage.getItem('r2-cart')||'[]').length)}catch{setCart(0)}};sync();const t=setInterval(sync,700);return()=>clearInterval(t)},[])
 useEffect(()=>{const query=typeof router.query.q==='string'?router.query.q:'';if(query!==search)setSearch(query)},[router.query.q])
 const submitSearch=e=>{e.preventDefault();const q=search.trim();router.push(q?`/products?q=${encodeURIComponent(q)}`:'/products')}
 const featured=useMemo(()=>picks.map(name=>products.find(p=>String(p.Title||'').toLowerCase().includes(name.toLowerCase().split(' ')[0]))).filter(Boolean).slice(0,3),[products])
 const add=p=>{try{const next=[...JSON.parse(localStorage.getItem('r2-cart')||'[]'),p];localStorage.setItem('r2-cart',JSON.stringify(next));setCart(next.length)}catch{}}
 return <>
  <Head><title>R2 NUSANTARA — Gudang Distributor Resmi Malang</title><meta name="description" content="R2 NUSANTARA — Gudang Distributor Resmi Malang. Portal informasi dan katalog B2B untuk mitra distribusi."/><meta name="theme-color" content="#06294A"/></Head>
  <main className="hx-page">
   <header className="hx-header"><Link href="/" className="hx-brand"><span className="hx-logo"><img src="/assets/logo/logo.png" alt="R2 NUSANTARA" width="48" height="48" /></span><span><b>R2 NUSANTARA</b><small>WHOLESALE TRADING PARTNER</small></span></Link><SearchBar value={search} onChange={e=>setSearch(e.target.value)} onSubmit={submitSearch}/><nav><a href="#benefits">KEUNGGULAN</a><a href="#system">SISTEM</a><a href="#picks">UNGGULAN</a><a href="#faq">FAQ</a><a href="#warehouse">GUDANG</a></nav><div className="hx-head-actions"><span className="hx-verified"><Icon name="check" size={15}/> Terverifikasi</span><Link href="/checkout" className="hx-cart">Keranjang <b>{cart}</b></Link><Link href="/products" className="hx-catalog">KATALOG →</Link></div></header>
   <section className="hx-hero"><div className="hx-hero-copy"><div className="hx-eyebrow"><span className="hx-blue-check">✓</span> OFFICIAL DISTRIBUTION <span>•</span> VERIFIED PARTNERS</div><h1>Wholesale,<br/>done <em>precisely.</em></h1><h2>Skala Bisnis Anda, <em>Gudang Kami Siap Penuhi.</em></h2><p>Portal informasi dan katalog R2 NUSANTARA dengan data produk live, struktur harga yang jelas, dan alur pemesanan yang dirancang untuk hubungan bisnis jangka panjang.</p><div className="hx-actions"><Link href="/products" className="hx-primary">BUKA KATALOG →</Link><Link href="/contact" className="hx-secondary">HUBUNGI ADMIN</Link></div></div><div className="hx-hero-panel"><div className="hx-panel-top"><span>R2 NUSANTARA</span><span className="hx-live"><i/> LIVE</span></div><strong>233</strong><span>MEREK READY STOCK</span><div className="hx-bars">{Array.from({length:24}).map((_,i)=><i key={i} style={{height:`${10+(i*13)%34}px`}}/>)}</div><small>GUDANG PUSAT · MALANG · JAWA TIMUR</small></div><SearchBar className="hx-hero-search" value={search} onChange={e=>setSearch(e.target.value)} onSubmit={submitSearch}/></section>
   <section className="hx-metrics" aria-label="Statistik utama"><a href="#testimonials"><strong>500+</strong><span>Mitra Toko</span><small>Dipercaya di Nusantara</small></a><a href="#picks"><strong>233</strong><span>Merek</span><small>Ready stock gudang pusat</small></a><a href="#benefits"><strong>1 BAL</strong><span>Gratis Ongkir</span><small>Minimal 20 slop</small></a><a href="#benefits"><strong>100%</strong><span>Original</span><small>Produk distributor resmi</small></a></section>
   <section className="hx-section" id="benefits"><div className="hx-section-head"><div><span>VALUE PROPOSITION</span><h2>Mengapa Mitra Memilih Kami</h2></div><p>Empat fondasi layanan yang dirancang untuk transaksi B2B.</p></div><div className="hx-benefit-grid">{benefits.map(([ico,title,sub,desc])=><article key={title}><div className="hx-card-icon"><Icon name={ico} size={22}/></div><h3>{title}</h3><b>{sub}</b><p>{desc}</p></article>)}</div></section>
   <section className="hx-section hx-system" id="system"><div className="hx-section-head"><div><span>TENTANG KAMI</span><h2>Sistem yang transparan.</h2></div></div><div className="hx-tabs">{tabs.map(([title],i)=><button key={title} className={tab===i?'active':''} onClick={()=>setTab(i)}>{title}</button>)}</div><article className="hx-tab-panel"><div className="hx-tab-number">0{tab+1}</div><div><h3>{tabs[tab][0]}</h3><p>{tabs[tab][1]}</p></div><Icon name={tab===0?'truck':tab===1?'box':'shield'} size={42}/></article></section>
   <section className="hx-section" id="picks"><div className="hx-section-head"><div><span>EDITOR'S PICK</span><h2>Koleksi Unggulan</h2></div><p>Data produk tetap berasal dari katalog live.</p></div><div className="hx-picks">{(featured.length?featured:products.slice(0,3)).map((p,i)=><article key={p['Variant SKU']||p.Handle||i}><div className="hx-pick-visual"><span>READY STOCK</span><strong>R2</strong><small>WHOLESALE</small></div><div className="hx-pick-body"><div className="hx-stars"><Icon name="star" size={14}/> <span>Unggulan</span></div><h3>{p.Title}</h3><p>{p.Type||p.Vendor||'Katalog R2 Nusantara'}</p><strong>{money(p['Variant Price'])}</strong><button onClick={()=>add(p)}>PESAN SEKARANG</button></div></article>)}</div></section>
   <section className="hx-proof" id="testimonials"><div><span>TESTIMONI MITRA</span><h2>Apa Kata 500+ Mitra Kami</h2><div className="hx-stars-lg">★★★★★ <small>Verified partner feedback</small></div></div><article className="hx-testimonial"><div className="hx-avatar">{testimonials[slide][0].split(' ').map(x=>x[0]).slice(0,2).join('')}</div><p>“{testimonials[slide][2]}”</p><strong>{testimonials[slide][0]}</strong><span>{testimonials[slide][1]}</span></article><div className="hx-slider"><button onClick={()=>setSlide((slide+testimonials.length-1)%testimonials.length)} aria-label="Testimoni sebelumnya">←</button>{testimonials.map((_,i)=><button key={i} className={i===slide?'active':''} onClick={()=>setSlide(i)} aria-label={`Testimoni ${i+1}`}/>) }<button onClick={()=>setSlide((slide+1)%testimonials.length)} aria-label="Testimoni berikutnya">→</button></div></section>
   <section className="hx-section hx-faq" id="faq"><div className="hx-section-head"><div><span>FAQ</span><h2>Pertanyaan Umum</h2></div></div><div className="hx-faq-grid">{faqs.map(([q,a],i)=><details key={q} open={open===i} onClick={e=>{e.preventDefault();setOpen(open===i?null:i)}}><summary>{q}<span>{open===i?'−':'+'}</span></summary>{open===i&&<p>{a}</p>}</details>)}</div></section>
   <section className="hx-warehouse" id="warehouse"><div className="hx-warehouse-copy"><span>GUDANG DISTRIBUTOR — R2 NUSANTARA</span><h2>Gudang Pusat Malang</h2><p>Kawasan Pergudangan Kota Malang, Jawa Timur, Indonesia.</p><div className="hx-meta"><span><Icon name="clock" size={16}/> Senin–Sabtu · 08.00–17.00 WIB</span><span><Icon name="check" size={16}/> Area loading & verifikasi</span><span><Icon name="map" size={16}/> Detail titik dikonfirmasi admin</span></div><Link href="/contact" className="hx-secondary">KONFIRMASI LOKASI →</Link></div><div className="hx-map"><iframe title="Preview peta Kota Malang" src="https://www.google.com/maps?q=Kota+Malang,+Jawa+Timur,+Indonesia&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><a href="https://www.google.com/maps/search/?api=1&query=Kota+Malang%2C+Jawa+Timur%2C+Indonesia" target="_blank" rel="noreferrer">BUKA GOOGLE MAPS →</a></div></section>
   <footer className="hx-footer"><div><span className="hx-footer-brand">R2 NUSANTARA</span><p>Gudang Distributor Resmi Malang</p></div><div><span>© 2026 R2 Nusantara. All rights reserved.</span><small>r2nusantara-shop.vercel.app</small></div><Link href="/products">KATALOG →</Link></footer>
  </main>
 </>
}
