import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabaseClient'

const COLUMNS='Handle,Title,Vendor,Type,Tags,Published,Option1 Name,Option1 Value,Variant SKU,Variant Price,"Variant Inventory Qty",Status'
const money=v=>Number.isFinite(Number(v))?new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v)):'Harga belum tersedia'
const stock=v=>Math.max(0,Number(v)||0)
function Icon({name,size=20}){const p={search:<><circle cx="11" cy="11" r="7.5"/><path d="m17 17 5 5"/></>,menu:<><path d="M4 6h16M4 12h16M4 18h16"/></>,close:<><path d="M5 5l14 14M19 5 5 19"/></>,cart:<><path d="M3 4h2l2.2 10.2a2 2 0 0 0 2 1.6h7.7a2 2 0 0 0 1.9-1.5L20 8H6"/><circle cx="9" cy="20" r="1.3"/><circle cx="17" cy="20" r="1.3"/></>,eye:<><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.4"/></>,sun:<circle cx="12" cy="12" r="4"/>,shield:<><path d="M12 3 20 6v5c0 5-3.3 8.6-8 10-4.7-1.4-8-5-8-10V6l8-3Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/></>,truck:<><path d="M3 6h11v10H3zM14 9h4l3 3v4h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></>,camera:<><path d="M4 7h4l1.5-2h5L16 7h4v11H4z"/><circle cx="12" cy="12.5" r="3.2"/></>,map:<><path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Z"/><path d="M9 3v15M15 6v15"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,check:<path d="m5 12 4 4L19 6"/>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[name]}</svg>}
const ProductVisual=({index=0})=><div className={`product-visual tone-${index%4}`}><span className="ready-ribbon">READY STOCK</span><span className="heart-static" aria-hidden="true">♡</span><div className="box-art"><span>R2</span><b>WHOLESALE</b><i>{String(index+1).padStart(2,'0')}</i></div></div>
const benefits=[['shield','Bayar Setelah Resi','Pembayaran dilakukan setelah resi terbit sesuai alur transaksi yang disepakati.'],['truck','Gratis Ongkir','Program subsidi ongkos kirim untuk minimal 1 bal (20 slop), sesuai ketentuan operasional.'],['check','233 Merek Ready','Katalog produksi aktif menampilkan produk yang tersedia dari database live.'],['shield','Produk Original','Informasi produk dan stok disajikan dari sumber katalog distributor yang terhubung.']]
const testimonials=[['H. Slamet Widodo','Toko Berkah Jaya, Surabaya','Sistem bayar setelah resi membuat proses pemesanan lebih tenang dan terstruktur.'],['Siti Rahmawati','Warung Bu Siti, Makassar','Program gratis ongkir 1 bal membantu perhitungan margin dan biaya kirim.'],['Budi Santoso','Toko Sumber Rezeki, Jakarta','Katalog lengkap, proses order jelas, dan admin responsif saat konfirmasi.'],['Agus Priyanto','Grosir AP, Medan','Sudah beberapa kali order dan alur katalog memudahkan pengecekan stok.'],['Dewi Lestari','Toko Dewi, Denpasar','Informasi gudang dan dokumentasi packing membantu proses verifikasi sebelum order.']]
const faqs=[['Apa itu sistem Bayar Setelah Resi Keluar?','Pembayaran dilakukan setelah barang masuk ekspedisi dan nomor resi terbit, mengikuti konfirmasi admin dan metode pembayaran yang tersedia.'],['Berapa minimal order untuk program gratis ongkir?','Minimal 1 bal (20 slop) dan dapat dikombinasikan antar-merek, sesuai ketentuan program yang berlaku.'],['Bagaimana alur pemesanan?','Pilih produk, masukkan ke keranjang, checkout, lalu admin mengonfirmasi detail pesanan melalui WhatsApp.'],['Ekspedisi apa saja yang tersedia?','JNE, J&T, SiCepat Express, dan Indah Cargo, dengan pilihan mengikuti tujuan dan karakteristik kiriman.'],['Berapa total pilihan merek?','Database produksi saat ini menampilkan 233 produk aktif. Pembagian kategori ditampilkan berdasarkan data katalog live.'],['Di mana lokasi gudang?','Gudang pusat berada di Kota Malang, Jawa Timur. Titik dan detail kunjungan diberikan melalui prosedur konfirmasi mitra.']]

export async function getServerSideProps({res}){res.setHeader('Cache-Control','public, s-maxage=10, stale-while-revalidate=59');const {data,count,error}=await supabase.from('R2 NUSANTARA').select(COLUMNS,{count:'exact'}).eq('Published',true).eq('Status','active').limit(8);return{props:{products:error?[]:data||[],count:count||0}}}

export default function HomePage({products,count}){
 const [query,setQuery]=useState(''),[cartCount,setCartCount]=useState(0),[selected,setSelected]=useState(null),[menu,setMenu]=useState(false),[toast,setToast]=useState('')
 useEffect(()=>{const sync=()=>{try{setCartCount(JSON.parse(localStorage.getItem('r2-cart')||'[]').length)}catch{setCartCount(0)}};sync();window.addEventListener('storage',sync);const t=setInterval(sync,700);return()=>{window.removeEventListener('storage',sync);clearInterval(t)}},[])
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return products.filter(p=>!q||[p.Title,p.Handle,p.Vendor,p.Type,p.Tags,p['Variant SKU']].filter(Boolean).join(' ').toLowerCase().includes(q))},[products,query])
 const addToCart=p=>{try{const next=[...JSON.parse(localStorage.getItem('r2-cart')||'[]'),p];localStorage.setItem('r2-cart',JSON.stringify(next));setCartCount(next.length);setToast(`${p.Title||p.Handle||'Produk'} ditambahkan ke keranjang`);setTimeout(()=>setToast(''),2200)}catch{}}
 return <><Head><title>R2 NUSANTARA — Wholesale Trading Partner</title><meta name="description" content="Portal B2B R2 Nusantara untuk mitra distribusi terverifikasi, dengan katalog live, informasi operasional, dan alur pemesanan profesional."/><meta name="theme-color" content="#fafaf8"/><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/></Head>
 <main className="r2-page">
  <header className="r2-nav"><Link href="/" className="r2-brand"><span className="r2-mark">R2</span><span><strong>R2 NUSANTARA</strong><small>WHOLESALE TRADING PARTNER</small></span></Link><nav className="r2-navlinks"><Link href="/">BERANDA</Link><Link href="/products">KATALOG</Link><a href="#partner">PARTNER</a><a href="#about">TENTANG</a><Link href="/contact">KONTAK</Link></nav><div className="r2-head-actions"><button className="r2-icon-btn" aria-label="Tampilan" title="Tampilan"><Icon name="sun" size={18}/></button><Link href="/checkout" className="r2-cart" aria-label="Keranjang"><Icon name="cart" size={19}/><b>{cartCount}</b></Link><button className="r2-menu-btn" onClick={()=>setMenu(v=>!v)} aria-label="Menu"><Icon name={menu?'close':'menu'} size={20}/></button><Link href="/products" className="r2-navcta">ACCESS CATALOG →</Link></div></header>
  {menu&&<div className="r2-mobile-menu"><Link href="/">BERANDA</Link><Link href="/products">KATALOG</Link><a href="#partner" onClick={()=>setMenu(false)}>PARTNER</a><a href="#about" onClick={()=>setMenu(false)}>TENTANG</a><Link href="/contact">KONTAK</Link></div>}
  <section className="r2-search"><Icon name="search" size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari produk, kategori, merk, atau SKU..." aria-label="Cari produk"/><kbd>⌘ K</kbd>{query&&<button onClick={()=>setQuery('')} aria-label="Hapus pencarian">×</button>}</section>
  <section className="r2-hero"><div><span className="r2-eyebrow">OFFICIAL DISTRIBUTION · VERIFIED PARTNERS</span><h1>Skala Bisnis Anda,<br/><em>Gudang Kami Siap Penuhi.</em></h1><p className="r2-lead">Akses katalog distribusi R2 Nusantara dengan data produk live, struktur harga yang jelas, dan alur pemesanan yang dirancang untuk hubungan bisnis jangka panjang.</p><div className="r2-actions"><Link href="/products" className="r2-btn primary">BUKA KATALOG →</Link><Link href="/contact" className="r2-btn secondary">MENJADI PARTNER</Link></div><div className="r2-trust"><span>◇ DATA LIVE</span><span>◇ MITRA TERVERIFIKASI</span><span>◇ DISTRIBUSI TERSTRUKTUR</span></div></div><aside className="r2-live"><div className="r2-livehead"><span><i className="r2-dot"/>LIVE CATALOG</span><span>SYS / 01</span></div><div className="r2-livevalue">{count}<span> ACTIVE SKUs</span></div><div className="r2-signal">{Array.from({length:28}).map((_,i)=><i key={i} style={{height:`${8+(i*17)%25}px`}}/>)}</div><div className="r2-livefoot"><span>CATALOG STATUS</span><strong>OPERATIONAL</strong></div></aside></section>
  <section className="r2-stat-strip"><div><strong>+500</strong><span>MITRA TOKO</span></div><div><strong>233</strong><span>PRODUK AKTIF</span></div><div><strong>4</strong><span>EKSPEDISI PARTNER</span></div><div><strong>1 BAL</strong><span>MIN. PROGRAM ONGKIR</span></div></section>
  <section className="r2-section" id="benefits"><div className="r2-sectionhead"><div><span className="r2-kicker">VALUE PROPOSITION</span><h2>Keunggulan sistem.</h2></div><span className="r2-sectionmeta">Dibangun untuk reseller & agen</span></div><div className="r2-benefits">{benefits.map(([icon,title,desc])=><article key={title}><div className="r2-feature-icon"><Icon name={icon} size={22}/></div><h3>{title}</h3><p>{desc}</p></article>)}</div></section>
  <section className="r2-section r2-about-grid" id="about"><div><span className="r2-kicker">WHY R2 NUSANTARA</span><h2>Sistem B2B tanpa proses yang berbelit.</h2><p className="r2-lead">R2 Nusantara memosisikan katalog sebagai data module untuk reseller dan agen: ringkas, transparan, cepat dipindai, dan menjaga identitas premium.</p></div><div className="r2-process"><article><span>01</span><h3>Subsidi Ongkos Kirim</h3><p>Program gratis ongkir mulai 1 bal (20 slop), mengikuti ketentuan operasional.</p></article><article><span>02</span><h3>Real-time Packing</h3><p>Dokumentasi foto dan video packing dapat digunakan sebagai bagian dari proses konfirmasi.</p></article><article><span>03</span><h3>Bayar Setelah Resi</h3><p>Tagihan diproses setelah barang masuk ekspedisi dan resi tersedia sesuai kesepakatan transaksi.</p></article></div></section>
  <section className="r2-section" id="picks"><div className="r2-sectionhead"><div><span className="r2-kicker">EDITOR'S PICK</span><h2>Koleksi unggulan.</h2></div><Link href="/products">VIEW ALL →</Link></div><div className="r2-grid">{filtered.slice(0,4).map((p,i)=><article className="r2-product" key={p['Variant SKU']||p.Handle||i}><ProductVisual index={i}/><div className="r2-body"><span className="r2-type">{p.Type||p.Vendor||'WHOLESALE'}</span><h3>{p.Title||p.Handle}</h3><div className="r2-price">{money(p['Variant Price'])}</div><span className="r2-stock">● STOK {stock(p['Variant Inventory Qty'])}</span></div><div className="r2-card-actions"><button type="button" onClick={()=>setSelected(p)}><Icon name="eye" size={15}/> DETAIL</button><button type="button" className="add" onClick={()=>addToCart(p)}><Icon name="cart" size={15}/> ADD TO CART</button></div></article>)}</div>{!filtered.length&&<div className="r2-empty">Produk tidak ditemukan. Coba kata kunci lain atau buka katalog lengkap.</div>}</section>
  <section className="r2-trustbanner" id="partner"><div className="r2-trusticon"><Icon name="shield" size={28}/></div><div><strong>Verified partner infrastructure.</strong><p>Catalog data is served from active production inventory and protected by database access policies.</p></div><Link href="/contact">PARTNER ACCESS →</Link></section>
  <section className="r2-section r2-testimonials" id="testimonials"><div className="r2-sectionhead"><div><span className="r2-kicker">SOCIAL PROOF</span><h2>Catatan dari mitra.</h2></div><span className="r2-sectionmeta">500+ toko di Indonesia</span></div><div className="r2-testimonial-grid">{testimonials.map(([name,place,quote])=><article key={name}><div className="r2-avatar">{name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><p>“{quote}”</p><strong>{name}</strong><span>{place}</span></article>)}</div></section>
  <section className="r2-section r2-faq" id="faq"><div className="r2-sectionhead"><div><span className="r2-kicker">FAQ</span><h2>Pertanyaan umum.</h2></div></div><div className="r2-faq-grid">{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  <section className="r2-warehouse" id="warehouse"><div className="r2-warehouse-icon"><Icon name="map" size={28}/></div><div><span className="r2-kicker">WAREHOUSE LOCATION</span><h2>Lokasi Gudang Fisik Kami.</h2><p>Transparansi adalah prioritas. Gudang Pusat R2 Nusantara berada di kawasan pergudangan Kota Malang, Jawa Timur, Indonesia.</p><div className="r2-warehouse-meta"><span><Icon name="clock" size={16}/> Senin–Sabtu · 08.00–17.00 WIB</span><span><Icon name="check" size={16}/> Area loading & verifikasi barang</span><span><Icon name="map" size={16}/> Kunjungan mitra dengan janji temu</span></div></div><Link href="/contact" className="r2-btn secondary">KONFIRMASI LOKASI →</Link></section>
  <footer className="r2-footer"><div><span className="r2-footer-brand">R2 NUSANTARA</span><p>Wholesale Distribution Partner · Data Live</p></div><div className="r2-footer-links"><Link href="/products">Katalog</Link><a href="#faq">FAQ</a><a href="#warehouse">Gudang</a><Link href="/contact">Kontak</Link></div><span>© {new Date().getFullYear()} R2 NUSANTARA</span></footer>
 </main>
 {selected&&<div className="r2-modal-backdrop" onClick={()=>setSelected(null)}><section className="r2-modal" onClick={e=>e.stopPropagation()}><button className="r2-modal-close" onClick={()=>setSelected(null)} aria-label="Tutup"><Icon name="close" size={20}/></button><ProductVisual index={0}/><span className="r2-type">{selected.Type||selected.Vendor||'WHOLESALE'}</span><h2>{selected.Title||selected.Handle}</h2><div className="r2-price">{money(selected['Variant Price'])}</div><p>SKU: {selected['Variant SKU']||'—'} · Stok: {stock(selected['Variant Inventory Qty'])}</p><button className="r2-modal-add" onClick={()=>{addToCart(selected);setSelected(null)}}><Icon name="cart" size={17}/> TAMBAH KE KERANJANG</button></section></div>}
 {toast&&<div className="r2-toast">✓ {toast}</div>}
 </> 
}
