create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id text not null references public.products(id) on delete cascade,
  image_url text,
  storage_path text,
  source_url text,
  verification_status text not null default 'pending' check (verification_status in ('pending','verified','rejected')),
  mime_type text,
  width integer,
  height integer,
  file_size_bytes bigint,
  sha256 text,
  alt_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(product_id)
);

create index if not exists product_images_status_idx on public.product_images(verification_status);
create index if not exists product_images_product_idx on public.product_images(product_id);

alter table public.product_images enable row level security;

drop policy if exists "public can read verified product images" on public.product_images;
create policy "public can read verified product images"
on public.product_images for select
to anon, authenticated
using (verification_status = 'verified');

insert into public.product_images (product_id, alt_text)
select p.id, p.name
from public.products p
where not exists (
  select 1 from public.product_images pi where pi.product_id = p.id
);

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;
